vim.g.mapleader = " "
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("n", "tk", ":bnext<enter>")
vim.keymap.set("n", "tj", ":bprev<enter>")
vim.keymap.set("n", "th", ":bfirst<enter>")
vim.keymap.set("n", "tl", ":blast<enter>")
vim.keymap.set("n", "td", ":bdelete<enter>")
vim.keymap.set('n', 'E', vim.diagnostic.open_float)
vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Move focus to the left window' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Move focus to the right window' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Move focus to the lower window' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Move focus to the upper window' })
